"""empty message

Revision ID: d752e51ce0da
Revises: 1d9fcc3486a2
Create Date: 2023-05-16 15:01:42.594155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd752e51ce0da'
down_revision = '1d9fcc3486a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'title')
    # ### end Alembic commands ###
